services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootpassword
      - MINIO_DEFAULT_BUCKETS=images

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_IMPORT: /tmp/plantswap-realm-export.json
    volumes:
      - ./realm-export.json:/tmp/plantswap-realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - postgres

  redis:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  plantswap:
    image: ghcr.io/schitcrafter/plantswap:latest
    environment:
      PLANTS_DATABASE_URL: postgres://postgres:postgres@postgres/plant_swap
      PLANTS_S3_ACCESS_KEY: root
      PLANTS_S3_SECRET_KEY: rootpassword
    ports:
      - 3000:3000
    depends_on: [postgres, redis, keycloak, minio]
    profiles: [ plantswap ]

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local
