log=info,auth=debug
base_url=http://localhost:3000/

[database]
url=postgres://postgres:postgres@localhost/plantswap

[s3]
endpoint=http://localhost:9000/
access_key=root
secret_key=rootpassword
images_bucket=images

[auth]
server_url=http://localhost:8080/realms/plantswap
client_id=plantswap
admin_role=admin

[plantnet]
api_url=https://my-api.plantnet.org/v2/

[redis]
url=redis://localhost:6379/
