name: Check backend code

on:
  push:
    branches: ['**']

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

defaults:
    run:
        working-directory: backend

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: actions/checkout@v4

      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo audit
