name: Build and push backend docker container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [ready_for_review]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/schitcrafter/plantswap
          flavor: latest=false
          tags: |
            type=raw,value=dev-latest,enable={{is_default_branch}}
            type=raw,value=dev-${{ github.run_number }},enable={{is_default_branch}}
            type=semver,pattern=release-v{{version}}
            type=ref,event=pr

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (alpine)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
